networks:
  local_dev:
    name: local_dev

services:
  api:
    container_name: rent-roll-api
    build:
      context: ./server
      dockerfile: Dockerfile
    develop:
      watch: 
        - action: rebuild
          path: ./server
    ports:
      - "5000:5000"
    networks:
      - local_dev
    depends_on:
      - db
    env_file:
      - .env

  db:
    container_name: rent-roll-db
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - "1433:1433"
    env_file:
      - .env
    networks:
      - local_dev
    volumes:
      - sql-data:/var/opt/mssql
    restart: unless-stopped

  webapp:
    container_name: rent-roll-webapp
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
      - /app/node_modules
    networks:
      - local_dev
    depends_on:
      - api

volumes:
  sql-data: