services:
  # asp.net web application
  webapp:
    container_name: rent-roll-api
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
  
  db:
    container_name: rent-roll-db
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: strongPassword123!
    volumes:
      - sql-data:/var/opt/mssql

volumes:
  sql-data: