### Get All
GET {{host}}/api/test
Accept: application/json

### Create Test
# @name createTest
POST {{host}}/api/test
Accept: application/json
Content-Type: application/json

{
    "name": "First Test",
    "secret": "Some user secret"
}

### Create Test - Bad Request (Required Field)
POST {{host}}/api/test
Accept: application/json
Content-Type: application/json

{
}

### Create Test - Bad Request (Max Length)
POST {{host}}/api/test
Accept: application/json
Content-Type: application/json

{
    "name": "Bad Request Test", 
    "secret": "Very long user secret that exceeds the maximum length of 20 characters"
}

### Get By Id
@id = {{createTest.response.body.id}}

GET {{host}}/api/test/{{id}}
Accept: application/json

### Get By Id - Not Found
GET {{host}}/api/test/2e67687e-4ab5-429c-af5a-6b3e0bc23090
Accept: application/json

### Unhandled Error
GET {{host}}/api/test/not-implemented
Accept: application/json