### Register test user (validation errors)
POST {{host}}/api/register
Accept: application/json
Content-Type: application/json

{
    "firstName": "",
    "lastName": "",
    "email": "invalid-email",
    "password": "123",
    "phoneNumber": "+123",
    "birthDate": "3000-01-01",
    "country": ""
}

### Register test user
POST {{host}}/api/register
Accept: application/json
Content-Type: application/json

{
    "firstName": "John",
    "lastName": "Doe",
    "email": "joedoe@gmail.com",
    "password": "Password123",
    "phoneNumber": "+1234567890",
    "birthDate": "1990-01-01",
    "country": "USA"
}

### Login user (validation errors)
POST {{host}}/api/login
Accept: application/json
Content-Type: application/json

{
    "email": "",
    "password": ""
}

### Login test user (user does not exist)
POST {{host}}/api/login
Accept: application/json
Content-Type: application/json

{
    "email": "nomail@gmail.com",
    "password": "Password123"
}

### Login test user (invalid password)
POST {{host}}/api/login
Accept: application/json
Content-Type: application/json

{
    "email": "joedoe@gmail.com",
    "password": "Password1234"
}

### Login test user (valid credentials)
# @name loginSuccess
POST {{host}}/api/login
Accept: application/json
Content-Type: application/json

{
    "email": "joedoe@gmail.com",
    "password": "Password123"
}

### Refresh token (validation errors)
POST {{host}}/api/refresh
Accept: application/json
Content-Type: application/json

{
    "accessToken": "",
    "refreshToken": ""
}

### Refresh token (valid token)
@accessToken = {{loginSuccess.response.body.accessToken}}
@refreshToken = {{loginSuccess.response.body.refreshToken}}

POST {{host}}/api/refresh
Accept: application/json
Content-Type: application/json

{
    "accessToken": "{{accessToken}}",
    "refreshToken": "{{refreshToken}}"
}

### Refresh token (invalid access token)
POST {{host}}/api/refresh
Accept: application/json
Content-Type: application/json

{
    "accessToken": "invalid-access-token",
    "refreshToken": "{{refreshToken}}"
}


### Refresh token (old refresh token)
POST {{host}}/api/refresh
Accept: application/json
Content-Type: application/json

{
    "accessToken": "{{accessToken}}",
    "refreshToken": "{{refreshToken}}"
}

### Logout user (unauthorized)
POST {{host}}/api/logout
Accept: application/json

### Logout user (authorized)
POST {{host}}/api/logout
Accept: application/json
Authorization: Bearer {{accessToken}}