@userEmail = joedoe@gmail.com
@userPassword = Password123
@adminEmail = dmytro.nikora@nure.ua
@adminPassword = Password_123

### Login test user (valid credentials)
# @name loginUser
POST {{host}}/api/authentication/login
Accept: application/json
Content-Type: application/json

{
    "email": "{{userEmail}}",
    "password": "{{userPassword}}"
}

### Login admin user
# @name loginAdmin
POST {{host}}/api/authentication/login
Content-Type: application/json

{
  "email": "{{adminEmail}}",
  "password": "{{adminPassword}}"
}

### Set token variables
@userToken = {{loginUser.response.body.accessToken}}
@adminToken = {{loginAdmin.response.body.accessToken}}

### Create mechanic (as admin, valid)
# @name createMechanic
POST {{host}}/api/mechanics
Authorization: Bearer {{adminToken}}
Content-Type: application/json

{
    "name": "Acting"
}

### Set mechanic id variable
@mechanicId = {{createMechanic.response.body.id}}

### Create mechanic (as user, forbidden)
POST {{host}}/api/mechanics
Authorization: Bearer {{userToken}}
Content-Type: application/json

{
    "name": "Sedan"
}

### Create mechanic (missing name, validation error)
POST {{host}}/api/mechanics
Authorization: Bearer {{adminToken}}
Content-Type: application/json

{
}

### Create mechanic (unauthorized, invalid token)
POST {{host}}/api/mechanics
Authorization: Bearer invalidtoken
Content-Type: application/json

{
    "name": "Coupe"
}

### Get all mechanics
GET {{host}}/api/mechanics?search=
Authorization: Bearer {{userToken}}

### Get mechanic by valid id
# @name getMechanic
GET {{host}}/api/mechanics/{{mechanicId}}
Authorization: Bearer {{userToken}}

### Get mechanic by invalid id (not found)
GET {{host}}/api/mechanics/2f277e8e-4ec5-49cd-b22d-2421f97dfb71
Authorization: Bearer {{userToken}}

### Update mechanic (as admin, valid)
PUT {{host}}/api/mechanics/{{mechanicId}}
Authorization: Bearer {{adminToken}}
Content-Type: application/json

{
    "name": "Alliances"
}

### Update mechanic (as user, forbidden)
PUT {{host}}/api/mechanics/{{mechanicId}}
Authorization: Bearer {{userToken}}
Content-Type: application/json

{
    "name": "User Update Attempt"
}

### Update mechanic (invalid id)
PUT {{host}}/api/mechanics/2f277e8e-4ec5-49cd-b22d-2421f97dfb71
Authorization: Bearer {{adminToken}}
Content-Type: application/json

{
    "name": "Nonexistent"
}

### Delete mechanic (as admin, valid)
DELETE {{host}}/api/mechanics/{{mechanicId}}
Authorization: Bearer {{adminToken}}

### Delete mechanic (as user, forbidden)
DELETE {{host}}/api/mechanics/{{mechanicId}}
Authorization: Bearer {{userToken}}