@userEmail = joedoe@gmail.com
@userPassword = Password123
@adminEmail = dmytro.nikora@nure.ua
@adminPassword = Password_123

### Login test user (valid credentials)
# @name loginUser
POST {{host}}/api/authentication/login
Accept: application/json
Content-Type: application/json

{
    "email": "{{userEmail}}",
    "password": "{{userPassword}}"
}

### Login admin user
# @name loginAdmin
POST {{host}}/api/authentication/login
Content-Type: application/json

{
  "email": "{{adminEmail}}",
  "password": "{{adminPassword}}"
}

### Set token variables
@userToken = {{loginUser.response.body.accessToken}}
@adminToken = {{loginAdmin.response.body.accessToken}}

### Get current user (unauthorized)
GET {{host}}/api/users/me
Authorization: Bearer invalid-token

### Get current user
# @name currentUser
GET {{host}}/api/users/me
Authorization: Bearer {{userToken}}

### Get current user
# @name currentAdmin
GET {{host}}/api/users/me
Authorization: Bearer {{adminToken}}

### Set user Id variables
@userId = {{currentUser.response.body.id}}
@adminId = {{currentAdmin.response.body.id}}

### Update current user (validation errors)
PUT {{host}}/api/users/me
Authorization: Bearer {{userToken}}
Content-Type: application/json

{
  "country": "",
  "lastName": "",
  "firstName": "",
  "birthDate": "3000-01-01T00:00:00Z",
  "email": "john.doe",
  "phoneNumber": "+1234501"
}

### Update current user
PUT {{host}}/api/users/me
Authorization: Bearer {{userToken}}
Content-Type: application/json

{
  "country": "USA",
  "lastName": "Doe_Updated",
  "firstName": "John_Updated",
  "birthDate": "1990-01-01",
  "email": "john.doe_updated@example.com",
  "phoneNumber": "+12345678901"
}

### Get all users (forbidden for non-admin)
GET {{host}}/api/users
Authorization: Bearer {{userToken}}

### Get all users
GET {{host}}/api/users
Authorization: Bearer {{adminToken}}

### Create admin user (validation errors)
POST {{host}}/api/users/admin
Authorization: Bearer {{adminToken}}
Content-Type: application/json

{
  "firstName": "",
  "lastName": "",
  "email": "alice.admin",
  "birthDate": "3000-01-01T00:00:00Z",
  "country": "",
  "password": "123",
  "phoneNumber": "+123"
}

### Create admin user (forbidden for non-admin)
POST {{host}}/api/users/admin
Authorization: Bearer {{userToken}}
Content-Type: application/json

{
  "firstName": "Alice",
  "lastName": "Admin",
  "email": "alice.admin@gmail.com",
  "birthDate": "1985-05-15",
  "country": "UK",
  "password": "SecurePass123!",
  "phoneNumber": "+441234567890"
}

### Create admin user
POST {{host}}/api/users/admin
Authorization: Bearer {{adminToken}}
Content-Type: application/json

{
  "firstName": "Alice",
  "lastName": "Admin",
  "email": "alice.admin@gmail.com",
  "birthDate": "1985-05-15",
  "country": "UK",
  "password": "SecurePass123!",
  "phoneNumber": "+441234567890"
}

### Block user by Id (forbidden for non-admin)
DELETE  {{host}}/api/users/{{userId}}
Authorization: Bearer {{userToken}}

### Block user by Id (forbidden to block admin)
DELETE  {{host}}/api/users/{{adminId}}
Authorization: Bearer {{adminToken}}

### Block user by Id
DELETE {{host}}/api/users/{{userId}}
Authorization: Bearer {{adminToken}}

### Get user by Id
GET {{host}}/api/users/{{userId}}
Authorization: Bearer {{adminToken}}